# Generated by Django 6.0 on 2025-12-18 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='deliveryType',
            field=models.CharField(choices=[('ordinary', 'Обычная доставка'), ('express', 'Экспресс доставка'), ('free', 'Бесплатная доставка')], default='ordinary', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='paymentType',
            field=models.CharField(choices=[('online', 'Онлайн картой'), ('someone', 'Онлайн со случайного чужого счета'), ('random', 'Онлайн со случайного счёта')], default='online', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('accepted', 'Принят'), ('confirmed', 'Подтвержден'), ('paid', 'Оплачен'), ('delivered', 'Доставлен'), ('cancelled', 'Отменен')], default='created', max_length=10),
        ),
    ]
