# Generated by Django 6.0 on 2025-12-25 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['parent'], name='products_ca_parent__f3c24e_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['title'], name='products_ca_title_80a91b_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category'], name='products_pr_categor_9edb3d_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['price'], name='products_pr_price_9b1a5f_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['rating'], name='products_pr_rating_c3ba71_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['available'], name='products_pr_availab_21d9ca_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['created_at'], name='products_pr_created_52f0d7_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['-rating'], name='products_pr_rating_1a2e15_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'price'], name='products_pr_categor_47b724_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['available', 'category'], name='products_pr_availab_2b7af0_idx'),
        ),
        migrations.AddIndex(
            model_name='productimage',
            index=models.Index(fields=['product'], name='products_pr_product_3d7874_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product'], name='products_re_product_b03620_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['date'], name='products_re_date_9813f4_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['rate'], name='products_re_rate_6007e6_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['-date'], name='products_re_date_7ac465_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', 'date'], name='products_re_product_a7db5d_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['product'], name='products_sa_product_1a39ef_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['dateFrom'], name='products_sa_dateFro_9a39b4_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['dateTo'], name='products_sa_dateTo_4ea391_idx'),
        ),
        migrations.AddIndex(
            model_name='sale',
            index=models.Index(fields=['-salePrice'], name='products_sa_salePri_421f94_idx'),
        ),
        migrations.AddIndex(
            model_name='specification',
            index=models.Index(fields=['product'], name='products_sp_product_3d4f56_idx'),
        ),
        migrations.AddIndex(
            model_name='specification',
            index=models.Index(fields=['name'], name='products_sp_name_c57ab6_idx'),
        ),
    ]
